# Inicializa la simulación
/run/initialize

# Configuración de la fuente de partículas
/gps/particle mu+
/gps/energy 1 GeV
/gps/position 0 0 0 m
/gps/direction 1 0 0

# Configuración de la visualización
/vis/open OGL    # Abre la visualización en OpenGL
/vis/viewer/set/viewpointVector 1 1 1  # Ajusta la perspectiva de la cámara
/vis/drawVolume   # Dibuja el volumen del detector
/vis/scene/add/trajectories smooth  # Añade las trayectorias de las partículas
/vis/scene/endOfEventAction accumulate  # Acumula la visualización para cada evento
/vis/viewer/set/autoRefresh true  # Refresca automáticamente después de cada evento

# Generar 10 eventos
/run/beamOn 10

# Mantener la visualización abierta al final de la simulación
/vis/viewer/set/autoRefresh false
/vis/scene/endOfRunAction keepCurrent

# Pausar la simulación para observar el resultado, sin terminarla abruptamente
/control/pause
